language: python
python:
  - "3.4"
# command to install dependencies
install:
    - python setup.py install test
    - pip install coveralls
# command to run tests
script:
    - coverage run --source=HookTest setup.py test
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi