language: python
python:
  - "3.4.5"
  - "3.5"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
deploy:
  provider: pypi
  user: sonofmun
  password: $PYPASS
  on:
    tags: true
