language: python
python:
  - "3.4.5"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls pycodestyle

# command to run tests
script:
    - coverage run setup.py test
    - pycodestyle --ignore E501 *.py HookTest
after_success:
    - coverage combine
    - coveralls
deploy:
  provider: pypi
  user: sonofmun
  password: $PYPASS
  on:
    tags: true
    python: "3.5"
